name: hekta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  flutter_styled_toast: ^2.1.3
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  page_transition: ^2.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: com
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
  uses-material-design: true
